/**
 * Created by ecook on 6/14/16.
 */
var _WXICON = {
    '00' : 'tornado',
    '01' : 'tropical-storm',
    '02' : 'tropical-storm',
    '03' : 'thunderstorm',
    '04' : 'thunderstorm',
    '05' : 'rain-snow',
    '06' : 'precip-wintry-mix',
    '07' : 'precip-wintry-mix',
    '08' : 'freezing-drizzle',
    '09' : 'light-rain',
    '10' : 'freezing-drizzle',
    '11' : 'rain',
    '12' : 'rain',
    '13' : 'flurries',
    '14' : 'snow',
    '15' : 'blowing-snow',
    '16' : 'snow',
    '17' : 'hail',
    '18' : 'precip-wintry-mix',
    '19' : 'fog',
    '20' : 'fog',
    '21' : 'fog',
    '22' : 'fog',
    '23' : 'wind',
    '24' : 'wind',
    '25' : 'sunny',
    '26' : 'cloudy',
    '27' : 'mostly-cloudy',
    '28' : 'mostly-cloudy',
    '29' : 'partly-cloudy',
    '30' : 'partly-cloudy',
    '31' : 'sunny',
    '32' : 'sunny',
    '33' : 'sunny',
    '34' : 'sunny',
    '35' : 'rain-hail',
    '36' : 'sunny',
    '37' : 'thunderstorm',
    '38' : 'thunderstorm',
    '39' : 'rain',
    '40' : 'rain',
    '41' : 'snow',
    '42' : 'snow',
    '43' : 'blowing-snow',
    '44' : 'na',
    '45' : 'rain',
    '46' : 'snow',
    '47' : 'thunderstorm'
}